---

- name: setup
  hosts: localhost
  tasks:
    - set_fact:
        username: "{{ ansible_user_id }}"

    - debug: msg="{{ ansible_distribution }}.yml {{ ansible_os_family }}.yml"

    - name: load os vars
      include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"


- name: super user actions
  hosts: localhost
  become: yes

  tasks:
    - name: update apt repository
      apt: update_cache=yes cache_valid_time=3600
      ignore_errors: yes

    - name: install packages
      apt: name={{item}} state=installed
      with_items:
        - vim
        - fish
        - python-pip
        - git
        - git-flow

    - name: install virtualfish pip package
      pip:
        name: virtualfish

    - name: install font
      copy:
        src: files/DejaVu Sans Mono Nerd Font Complete Mono.ttf
        dest: /usr/share/fonts/truetype/dejavu/
    
    - name: set fish as default shell
      user:
        name: "{{ username }}"
        shell: /usr/bin/fish

    - check if ccat is installed:
      stat: path=/usr/bin/ccat
      register: ccat

    - name: install ccat
      get_url:
        url: "{{ ccat_url }}"
        dest: /tmp/ccat.tar.gz
      when: ccat.stat.exists == False

    - name: unpack ccat
      raw: "cd /tmp && tar -xzvf ccat.tar.gz {{ ccat_dir }}/ccat && mv {{ ccat_dir }}/ccat /usr/bin/ccat && rm -r ccat.tar.gz {{ ccat_dir }}"
      when: ccat.stat.exists == False


- name: user actions
  hosts: localhost
  vars:
    path: /tmp/ansible

  tasks:
    - name: check if omf is installed
      raw: fish -c 'omf'
      ignore_errors: True
      register: omf

    - debug: msg="{{omf}}"

    - set_fact:
        install_omf: "{{ omf.rc != 0 }}"

    - debug: msg="Oh my Fish already installed"
      when: not install_omf

    - name: create a temp folder
      tempfile:
        state: directory
      register: mktempd
      when: install_omf

    - set_fact:
        path: "{{ mktempd.path }}"
      when: install_omf

    - debug:
        msg: "Temp folder: {{ path }}"
      when: install_omf

    - name: get omf
      get_url:
        url: https://get.oh-my.fish
        dest: "{{ path }}"
      when: install_omf

    - name: install omf
      raw: "fish {{ path }}/install --noninteractive -y"
      when: install_omf

    - name: create virtualenvs folder
      file:
        path: ~/.virtualenvs
        state: directory

    - name: install omf packages
      with_items:
        - z
        - bobthefish
        - https://github.com/jhillyerd/plugin-git
        - https://github.com/rettier/phish.git
        - virtualfish
      raw: fish -c 'omf install {{item}}; omf update {{item}}'

    - name: set bobthefish theme
      raw: fish -c 'omf theme bobthefish'

    - name: set gnome terminal profile
      raw: "fish -c 'dconf load /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/ < files/terminal-profile.dconf'"

    - name: set mate terminal profile
      raw: "bash -c 'cd files; ./mate-terminal-profile.sh'"

    - name: delete temp folder
      file:
        path: "{{ path }}"
        state: absent
      when: install_omf